const FILTERS_NAMESPACE = "FILTERS-TRIP";

export const UPDATE_COUNTRY: string = `${FILTERS_NAMESPACE}/UPDATE_COUNTRY`;
export const UPDATE_START_DATE: string = `${FILTERS_NAMESPACE}/UPDATE_START_DATE`;
export const UPDATE_END_DATE: string = `${FILTERS_NAMESPACE}/UPDATE_END_DATE`;

export const CLEAR_FILTERS: string = `${FILTERS_NAMESPACE}/CLEAR_FILTERS`;
export const SEARCH: string = `${FILTERS_NAMESPACE}/SEARCH`;
